server:
  port: 9001   #设置的端口号

#在注册中心发布的名字
spring:
  application:
    name: nacos-payment-provider
management:
  endpoints:
    web:
      exposure:
        include: '*'  #默认只公开了/health和/info端点，要想暴露所有端点只需设置成星号