server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-service #在注册中心eureka中的名字

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/  #调用的地址